name: dinovdeau_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas==2.2.3
      - kornia==0.7.3
      - datasets==3.0.2
      - huggingface-hub==0.27.1
      - transformers==4.48.0
      - scikit-learn==1.5.2
      - tensorboardX==2.6.2.2
      - accelerate==1.0.1
      - tabulate==0.9.0
      - ipykernel==6.29.5
      - pillow==11.0.0
      - importlib-resources==6.4.5
